spring:
  application:
    name: webflux-eureka-client

server:
  port: ${server-port:8080}

http:
  protocol: ${http-protocol:https}

eureka:
  #hostname: ${eureka-instance-hostname:localhost:${server.port}}
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eureka-client-service-url:https://jjara-eureka-basic.herokuapp.com/eureka}
  instance:
    instanceId: ${spring.application.name}:${eureka.hostname}
    statusPageUrl: ${http.protocol}://${eureka.hostname}/actuator/info
    healthCheckUrl: ${http.protocol}://${eureka.hostname}/actuator/health
    homePageUrl: ${http.protocol}://${eureka.hostname}/

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
instance:
  id: ${instance-id:local}
