server:
  port: 8762

spring:
  application:
    name: zuul-server
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: webflux-eureka-clients
          uri: lb://webflux-eureka-clients
          predicates:
            - Path=/**

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eureka-client-serviceUrl-defaultZone:https://jjara-eureka-basic.herokuapp.com/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    routes:
      enabled: true
    filters:
      enabled: true