server:
  port: ${server-port:8080}

spring:
  application:
    name: gateway-eureka-lb
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: webflux-eureka-client
          uri: lb://webflux-eureka-client
          predicates:
            - Path=/customer/**
          filters:
            - RewritePath=/customer(?<segment>/?.*), $\{segment}
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eureka-client-serviceUrl-defaultZone}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    routes:
      enabled: true
    filters:
      enabled: true
