spring:
  application:
    name: webflux-eureka-client

server:
  port: ${server-port:8080}

http:
  protocol: ${http-protocol:https}

eureka:
  instance:
    #hostname: ${DOMAIN_NAME}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    fetch-registry: false
    register-with-eureka: false
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: ${eureka-client-service-url:https://jjara-eureka-basic.herokuapp.com/eureka}

management:
  endpoints:
    web:
      exposure:
        include: "*"
        
instance:
  id: ${instance-id:local}
